/**
 * This script reads the theme SCSS files and generates a TypeScript file
 * containing the CSS variables as strings for the UnoCSS preset preflight.
 *
 * Run: npx tsx scripts/generate-unocss-css-vars.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

function getArgValue(name: string): string | undefined {
  const index = process.argv.indexOf(name)
  if (index === -1)
    return
  return process.argv[index + 1]
}

const THEME_DIR = path.resolve(
  getArgValue('--wot-dir')
  ?? path.resolve(__dirname, '../src/uni_modules/wot-ui/styles/theme'),
)
const OUTPUT_FILE = path.resolve(
  getArgValue('--output')
  ?? path.resolve(__dirname, '../src/generated/css-vars.ts'),
)

function extractCssVars(content: string): string[] {
  const vars: string[] = []
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed.startsWith('--wot-') || !trimmed.endsWith(';'))
      continue
    const colonIndex = trimmed.indexOf(':')
    if (colonIndex === -1)
      continue
    const name = trimmed.slice(0, colonIndex).trim()
    const value = trimmed.slice(colonIndex + 1, -1).trim()
    if (!name || !value)
      continue
    vars.push(`  ${name}: ${value};`)
  }
  return vars
}

function readAndExtract(filePath: string): string[] {
  const content = fs.readFileSync(filePath, 'utf8')
  return extractCssVars(content)
}

// Base variables
const baseFiles = ['color.scss', 'number.scss', 'font.scss', 'opacity.scss', 'radius.scss', 'insets.scss', 'stroke.scss', 'typography.scss']
const baseVars: string[] = []
for (const file of baseFiles) {
  baseVars.push(...readAndExtract(path.join(THEME_DIR, 'base', file)))
}

// Light semantic variables
const lightVars = readAndExtract(path.join(THEME_DIR, 'light.scss'))

// Dark semantic variables
const darkVars = readAndExtract(path.join(THEME_DIR, 'dark.scss'))

const BASE_CSS = `:root, page, .wd-root-portal {\n${baseVars.join('\n')}\n}`
const LIGHT_CSS = `:root, page, .wd-root-portal {\n${lightVars.join('\n')}\n}`
const DARK_CSS = `.wot-theme-dark, .wot-theme-dark .wd-root-portal {\n${darkVars.join('\n')}\n}`

const output = `// Auto-generated by scripts/generate-unocss-css-vars.ts — DO NOT EDIT
export const BASE_CSS_VARS = ${JSON.stringify(BASE_CSS)}

export const LIGHT_CSS_VARS = ${JSON.stringify(LIGHT_CSS)}

export const DARK_CSS_VARS = ${JSON.stringify(DARK_CSS)}
`

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
fs.writeFileSync(OUTPUT_FILE, output, 'utf8')
console.log(`Generated: ${OUTPUT_FILE}`)
